name: Update Progress Chart

on:
  push:
    branches:
      - main

jobs:
  update-chart:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install matplotlib

      - run: python progress.py

      - name: Commit Chart
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add progress.png

          git commit -m "Update progress chart" || exit 0

          git push